//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uWaveCommander {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalisedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalisedStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uWaveCommander.LocalisedStrings", typeof(LocalisedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close application?.
        /// </summary>
        internal static string MainForm_ApplicationClosePrompt {
            get {
                return ResourceManager.GetString("MainForm_ApplicationClosePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на entry(s) was/were deleted.
        /// </summary>
        internal static string MainForm_EntriesWereDeleted {
            get {
                return ResourceManager.GetString("MainForm_EntriesWereDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string MainForm_Error {
            get {
                return ResourceManager.GetString("MainForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на file(s) was/were deleted.
        /// </summary>
        internal static string MainForm_FilesWereDeleted {
            get {
                return ResourceManager.GetString("MainForm_FilesWereDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        internal static string MainForm_Information {
            get {
                return ResourceManager.GetString("MainForm_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a name of an archive to store all log files....
        /// </summary>
        internal static string MainForm_LogArchiveDialogTitle {
            get {
                return ResourceManager.GetString("MainForm_LogArchiveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All log files archived:.
        /// </summary>
        internal static string MainForm_LogArchiveResult {
            get {
                return ResourceManager.GetString("MainForm_LogArchiveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to delete all log files? (this action cannot be undone!).
        /// </summary>
        internal static string MainForm_LogDeleteAllEntriesPrompt {
            get {
                return ResourceManager.GetString("MainForm_LogDeleteAllEntriesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all log files smaller than 2 kB and empty folders?.
        /// </summary>
        internal static string MainForm_LogDeleteEmptyEntriesPrompt {
            get {
                return ResourceManager.GetString("MainForm_LogDeleteEmptyEntriesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log file.
        /// </summary>
        internal static string MainForm_LogFile {
            get {
                return ResourceManager.GetString("MainForm_LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There were some problems while creating an archive file, log files were not deleted.
        /// </summary>
        internal static string MainForm_LogMoveToArchiveProblemsResult {
            get {
                return ResourceManager.GetString("MainForm_LogMoveToArchiveProblemsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log files were moved to archive:.
        /// </summary>
        internal static string MainForm_LogMoveToArchiveResult {
            get {
                return ResourceManager.GetString("MainForm_LogMoveToArchiveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A log file is currently playing, abort it?.
        /// </summary>
        internal static string MainForm_LogPlaybackAbortPrompt {
            get {
                return ResourceManager.GetString("MainForm_LogPlaybackAbortPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a log file to playback....
        /// </summary>
        internal static string MainForm_LogPlaybackSelectDialogTitle {
            get {
                return ResourceManager.GetString("MainForm_LogPlaybackSelectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        internal static string MainForm_LogPlaybackStopBtnText {
            get {
                return ResourceManager.GetString("MainForm_LogPlaybackStopBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to move all log file to an archive?.
        /// </summary>
        internal static string MainForm_MoveLogsToArchivePrompt {
            get {
                return ResourceManager.GetString("MainForm_MoveLogsToArchivePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a name of archive to store all log files....
        /// </summary>
        internal static string MainForm_MoveLogsToArchivePromptTitle {
            get {
                return ResourceManager.GetString("MainForm_MoveLogsToArchivePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playback....
        /// </summary>
        internal static string MainForm_Playback {
            get {
                return ResourceManager.GetString("MainForm_Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PLayback is finished.
        /// </summary>
        internal static string MainForm_PlaybackIsFinished {
            get {
                return ResourceManager.GetString("MainForm_PlaybackIsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Question.
        /// </summary>
        internal static string MainForm_Question {
            get {
                return ResourceManager.GetString("MainForm_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings has been saved. Restart application to apply new settings?.
        /// </summary>
        internal static string MainForm_RestartPrompt {
            get {
                return ResourceManager.GetString("MainForm_RestartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Screenshot saved.
        /// </summary>
        internal static string MainForm_ScreenshotSaved {
            get {
                return ResourceManager.GetString("MainForm_ScreenshotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string MainForm_Settings {
            get {
                return ResourceManager.GetString("MainForm_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning!.
        /// </summary>
        internal static string MainForm_Warning {
            get {
                return ResourceManager.GetString("MainForm_Warning", resourceCulture);
            }
        }
    }
}
